/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#D1DAD7',
        surface: '#FFFFFF',
        cream: '#F2EEE2',
        primary: '#678770',
        'primary-dark': '#557561',
        sage: '#8FA99A',
        beige: '#D9D5B8',
        income: '#678770',
        expense: '#B87568',
        'text-primary': '#303632',
        'text-secondary': '#7B817C',
        'pastel-red': '#FFB3BA',
        'pastel-orange': '#FFDFBA',
        'pastel-green': '#BAFFC9',
        'pastel-blue': '#BAE1FF',
        'pastel-purple': '#D5AAFF',
        'pastel-pink': '#FFC4E1',
        'pastel-teal': '#A2E1DB',
        'pastel-peach': '#FFD3B6',
        'pastel-lavender': '#E6B3FF',
      },
      borderRadius: {
        'xl2': '20px',
        '2xl': '24px'
      },
      boxShadow: {
        'soft': '0 8px 30px rgba(85, 117, 97, 0.12)',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      }
    },
  },
  safelist: [
  'bg-primary',
  'bg-primary/20',
  'bg-primary/30',
  'bg-primary/40',
  'bg-primary/50',
  'bg-primary/60',
  'bg-primary/70',
  'bg-primary/80',
  'bg-primary/90',
  'bg-sage',
  'bg-sage/20',
  'bg-sage/30',
  'bg-sage/40',
  'bg-sage/50',
  'bg-sage/60',
  'bg-sage/70',
  'bg-sage/80',
  'bg-sage/90',
  'bg-beige',
  'bg-beige/20',
  'bg-beige/30',
  'bg-beige/40',
  'bg-beige/50',
  'bg-beige/60',
  'bg-beige/70',
  'bg-beige/80',
  'bg-beige/90',
  'bg-expense',
  'bg-expense/20',
  'bg-expense/30',
  'bg-expense/40',
  'bg-expense/50',
  'bg-expense/60',
  'bg-expense/70',
  'bg-expense/80',
  'bg-expense/90',
  'bg-cream',
  'bg-cream/20',
  'bg-cream/30',
  'bg-cream/40',
  'bg-cream/50',
  'bg-cream/60',
  'bg-cream/70',
  'bg-cream/80',
  'bg-cream/90',
  'bg-primary-dark',
  'bg-primary-dark/20',
  'bg-primary-dark/30',
  'bg-primary-dark/40',
  'bg-primary-dark/50',
  'bg-primary-dark/60',
  'bg-primary-dark/70',
  'bg-primary-dark/80',
  'bg-primary-dark/90',
  'bg-pastel-red',
  'bg-pastel-red/20',
  'bg-pastel-red/30',
  'bg-pastel-red/40',
  'bg-pastel-red/50',
  'bg-pastel-red/60',
  'bg-pastel-red/70',
  'bg-pastel-red/80',
  'bg-pastel-red/90',
  'bg-pastel-orange',
  'bg-pastel-orange/20',
  'bg-pastel-orange/30',
  'bg-pastel-orange/40',
  'bg-pastel-orange/50',
  'bg-pastel-orange/60',
  'bg-pastel-orange/70',
  'bg-pastel-orange/80',
  'bg-pastel-orange/90',
  'bg-pastel-green',
  'bg-pastel-green/20',
  'bg-pastel-green/30',
  'bg-pastel-green/40',
  'bg-pastel-green/50',
  'bg-pastel-green/60',
  'bg-pastel-green/70',
  'bg-pastel-green/80',
  'bg-pastel-green/90',
  'bg-pastel-blue',
  'bg-pastel-blue/20',
  'bg-pastel-blue/30',
  'bg-pastel-blue/40',
  'bg-pastel-blue/50',
  'bg-pastel-blue/60',
  'bg-pastel-blue/70',
  'bg-pastel-blue/80',
  'bg-pastel-blue/90',
  'bg-pastel-purple',
  'bg-pastel-purple/20',
  'bg-pastel-purple/30',
  'bg-pastel-purple/40',
  'bg-pastel-purple/50',
  'bg-pastel-purple/60',
  'bg-pastel-purple/70',
  'bg-pastel-purple/80',
  'bg-pastel-purple/90',
  'bg-pastel-pink',
  'bg-pastel-pink/20',
  'bg-pastel-pink/30',
  'bg-pastel-pink/40',
  'bg-pastel-pink/50',
  'bg-pastel-pink/60',
  'bg-pastel-pink/70',
  'bg-pastel-pink/80',
  'bg-pastel-pink/90',
  'bg-pastel-teal',
  'bg-pastel-teal/20',
  'bg-pastel-teal/30',
  'bg-pastel-teal/40',
  'bg-pastel-teal/50',
  'bg-pastel-teal/60',
  'bg-pastel-teal/70',
  'bg-pastel-teal/80',
  'bg-pastel-teal/90',
  'bg-pastel-peach',
  'bg-pastel-peach/20',
  'bg-pastel-peach/30',
  'bg-pastel-peach/40',
  'bg-pastel-peach/50',
  'bg-pastel-peach/60',
  'bg-pastel-peach/70',
  'bg-pastel-peach/80',
  'bg-pastel-peach/90',
  'bg-pastel-lavender',
  'bg-pastel-lavender/20',
  'bg-pastel-lavender/30',
  'bg-pastel-lavender/40',
  'bg-pastel-lavender/50',
  'bg-pastel-lavender/60',
  'bg-pastel-lavender/70',
  'bg-pastel-lavender/80',
  'bg-pastel-lavender/90'
],
  plugins: [],
}
